### PR TITLE
Add german Wordlist

### PR DESCRIPTION
**Pull request by anlx-sw**
German Wordlist - nearly 10k words

### CODE REVIEW

**Comment by anlx-sw** [comment]
Modification of https://github.com/dassencio/langcmp/blob/master/wordlists/top1000de.txt (GPL-3.0).
Removed one or two char long entries and words with blank space in between.

**Comment by florianjacob** [comment]
Big 👍 for working on a decent german wordlist, as there are almost no usable lists for our purpose, the only one I know of is [a german version of Diceware](http://world.std.com/~reinhold/diceware_german.txt), but it has similar problems like what's discussed for the english diceware list in [the blog post for the eff wordlist](https://www.eff.org/de/deeplinks/2016/07/new-wordlists-random-passphrases).

Do you have prior experience with your wordlist? Does it work out?

Removing one and two char entries already helped a lot I guess, but I'm not sure how memorable the passwords are that you get when there are words in there that only differ in spelling, e.g. `daß`, `Daß`, `das`, `Das`, `dass`, `Dass` are all in there, or plural forms like `Gruppe` and `Gruppen` (group / groups) or conjugated forms of verbs / adjectives like ` Gehen`, `gehen`, `geht`, `ging` (to go). `speziell`, `spezielle`, `speziellen` (special).

Those were just random words I checked - the actual extent of this problem would be much more evident if the wordlist was not sorted by frequency, but alphabetically like in a lexicon, with [`a` followed by `ä` etc](https://de.wikipedia.org/wiki/Alphabetische_Sortierung#Deutsche_Sprache).
(Also, the other word lists are in that order as well, I think.)

To all German-speaking countries, cheers 🍻! 🇩🇪🇦🇹🇨🇭 😄

**Comment by anlx-sw** [comment]
In my opinion it creates some nice passphrases - i used it for some. you can try for yourself with `xkcdpass -w /path/toger-anlx -c 20`. the only problems i had were with some "german umlauts" which are not correctly encoded by my python installation. I don't know if this is a general problem.

i sorted the wordlist and created a patch diff file here if you want to check for plural/conjugated forms: 
https://github.com/anlx-sw/XKCD-password-generator/blob/patch-1/xkcdpass/static/ger-anlx-sorted

if i understand the diceware concept correctly there should be no big security implication - as the words differ.

**Comment by anlx-sw** [comment]
# xkcdpass -c 20 -w ger-anlx-sorted  
ihres Junge werden Weise Bayern Volker
Gefühlen goldenen jetzigen Intel Major interne
entfalten Klavier perfekt Auschwitz gegangen Ansätze
Gutes Mittwoch Dietrich direkt schlechte Lager
traut Energie Romantik Palast Flügel Agenten
März Licht mögen braucht Umfeld Christine
Bauch verbinden Bundes Kabul fürchtet Kabel
sehen nämlich Mainz eintreten kritisch Inhaber
Schritte Karte Verbot Umbau bewiesen normalen
zumal Maßnahme Christel pflegt winzigen heimlich
Angebote Weltmarkt Atlanta beträgt hierzu Hitler
weiße eines riesige gestattet Wunder Monate
Grosny Anbietern William Freilich geriet Helfer
Zahlungen Kammer denke Zudem moderner Städten
starkes Verzicht genauen Koffer Kurse auswirken
somit Ehemann schweren Natur scheitern befragt
Legende Planeten Museen Studie oftmals Neuwahlen
mußten daraufhin geredet Abzug unsicher zunehmend
gewordene geschehen Börse besser hängen Details
regieren falschen entsprach Gerade berichten krank

**Comment by redacted** [comment]
Thanks for the wordlist, it'll be pushed in the next release

**Pull request merged**
