### PR TITLE
Put the password generation into a closure

### PR DESCRIPTION
**Pull request by mcfedr**
Also put the actual password generation into a closure because its gotten more complicated and is duplicated because if the interactive mode

### CODE REVIEW

**Comment by redacted** [comment]
Hey, thanks for the PR. The capitalize option has been suggested before e.g., https://github.com/redacted/XKCD-password-generator/pull/63. There are a lot of potentially useful transforms so the solution settled on in that issue - using the importable library functionality, or a secondary wrapper script, seems preferable to me.

I do like the closure fix though - would you consider opening a new PR with just that change?

**Comment by mcfedr** [comment]
Hmm, that would make my simple CLI usage of this otherwise perfect tool more complicated. I am a fan of the no spaces style `HamsterBarbecueSubstanceShucking`

**Comment by bonki** [comment]
$ sed -re 's#\b(.)#\U\1#g' -e 's#\s+##g' <<< "foo bar quux"
    FooBarQuux

**Comment by mcfedr** [comment]
Updated the PR with just the closure change

**Comment by mcfedr** [comment]
@bonki Thanks, I have had to use `awk` version as `sed` on mac os is missing `-r` option.

```
xkcdpass | awk '{for (i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) substr($i,2); gsub(/ /, "", $0); print}'
```

**Comment by redacted** [comment]
Thanks for this, merged and in the next release

**Pull request merged**
