### PR TITLE
as-is case

### PR DESCRIPTION
**Pull request by chkpnt**
It would be nice to have an option to keep the case as given in the wordlist.

At least in the German wordlist, lots of words are already capitalized as nouns are always capitalized.

Furthermore, I've added two missing tests and did some chore regarding PEP8 which my IDE (PyCharm) observed.

### CODE REVIEW

**Comment by chkpnt** [comment]
Btw: test_loadwordfile fails on my machine.

`xkcd_password` doesn't find the passed wordlist, so it uses `eff-long`, which results in a length of 5670.

grafik

But dunno, may be it's just a configuration issue on my side, so I haven't changed anything.

**Comment by Sol7469** [comment]
I just wanted to submit a pull request for this. Then I saw, there is already one. My solution is nearly the same.
I would realy appreciate this new option for switching case.

Thanks @chkpnt

**Comment by chkpnt** [comment]
Any thoughts about this, @redacted?

**Comment by redacted** [comment]
Hey, apologies for the delay in getting back to you on this. Looks good to me, merged!

**Pull request merged**
