### PR TITLE
Add option to Capitalize every word generated

### PR DESCRIPTION
**Pull request by lepickle**

### CODE REVIEW

**Comment by redacted** [comment]
Thanks for the PR. Have you looked at the examples/ directory in the repo? I think you could more easily solve your use case working from either the `example_import` or `example_postprocess` scripts

**Comment by lepickle** [comment]
Sure, is it alright to add it to example_import?

**Comment by redacted** [comment]
Of course, go ahead! The more examples the better

**Comment by lepickle** [comment]
Thanks! Sorry for the late reply, I got stacked at work but I'll be merging the new code in a while.

**Comment by lepickle** [comment]
Hello, sorry for the late PR. I moved everything to the examples scripts instead.

**Comment by lepickle** [comment]
Crap, I accidentally closed the PR.

**Comment by redacted** [comment]
Thanks for that, merged now!

**Pull request merged**
